import { settingsOnboarded } from 'api/settingsApi';
import Dates from 'components/dates/Dates';
import RestaurantDropdownEmpty from 'components/restaurantDropdown/RestaurantDropdownEmpty';
import OnboardingModal from 'components/settings/onboarding/OnboardingModal';
import OnboardingStepper from 'components/settings/onboarding/OnboardingStepper';
import useTableContentFormatter from 'components/tableRevly/tableContentFormatter/useTableContentFormatter';
import TableRevlyNew from 'components/tableRevly/TableRevlyNew';
import Widget from 'components/widget/Widget';
import { usePlatform, useUser } from 'contexts';
import { format, getYear } from 'date-fns';
import { enUS } from 'date-fns/locale';
import dayjs from 'dayjs';
import { useDate } from 'hooks';
import { ContainerKit, TypographyKit } from 'kits';
import { useEffect, useState } from 'react';
import { useNavigate } from 'react-router-dom';
import './Dashboard.scss';

const links = [
  { title: 'Revenue', link: 'revenue', tooltip: 'Revenue generated by the offer' },
  { title: 'Orders', link: 'n_orders', tooltip: '# of orders generated by the offer' },
  { title: 'Avg. basket', link: 'average_basket' },
  { title: 'Accrued discount', link: 'accrued_discounts' },
  {
    title: 'Ads spend',
    link: 'accrued_ads',
    tooltip:
      'The total budget spent on advertising (CPC and premium positions) across all platforms',
  },
  {
    title: 'Return on Ads Spend',
    link: 'roas',
    tooltip:
      'The amount of revenue earned for every AED invested in advertising (CPC, premium positions)',
  },
  {
    title: 'Net revenue',
    link: 'profit',
    tooltip: `Revenue generated by the offer minus aggregator's commission, discounts amount, ads CPC and food cost.`,
  },
  {
    title: 'Return on investment',
    link: 'roi',
    tooltip: `# AED generated in Profits for every 1 AED spent on discount. Profits are revenue minus aggregator's commission, order discount, ads CPC and food cost.`,
  },
];

const Dashboard = () => {
  const [table, setTable] = useState('revenue');

  const [openedModal, setOpenedModal] = useState(false);
  const [activeStep, setActiveStep] = useState(0);
  const [branchDataUploading, setBranchDataUploading] = useState([]);
  const [branchData, setBranchData] = useState([]);
  const [accounts, setAccounts] = useState([]);
  const [connectAccount, setConnectAccount] = useState('account');
  const [connect, setConnect] = useState('');
  const user = useUser();
  const { renderPlatform, renderSimpleRow, renderPlatformSkeleton, renderSimpleRowSkeleton } =
    useTableContentFormatter();

  const openCloseModal = () => {
    setOpenedModal(!openedModal);

    if (connectAccount === 'manageBranch' || connectAccount === 'completed') {
      setConnectAccount('account');
    }

    const body = document.querySelector('body');
    const navbar = document.querySelector('.Navbar');

    if (!openedModal) {
      navbar.classList.add('openedModal');
      body.style.overflowY = 'hidden';
      return;
    }

    body.style.overflowY = 'visible';
  };

  const propsVariables = {
    openCloseModal,
    setConnect,
    connect,
    setAccounts,
    accounts,
    setBranchData,
    branchData,
    setBranchDataUploading,
    branchDataUploading,
    setActiveStep,
    activeStep,
    openedModal,
    connectAccount,
    setConnectAccount,
  };

  const { userPlatformData, setUserPlatformData } = usePlatform();
  const { date } = useDate();
  const { typeDate } = date;
  const getPeriod = (title, period) => {
    if (title === 'custom') {
      if (typeDate === 'day') {
        return `${dayjs(period.startDate).format('DD/MM')}`;
      }
      if (typeDate === 'month') {
        return `${format(new Date(period.startDate), 'LLL', { locale: enUS })}  -  ${getYear(
          new Date(period.startDate)
        )}`;
      }

      return `${dayjs(period.startDate).format('DD/MM')} - ${dayjs(period.endDate).format(
        'DD/MM'
      )}`;
    }

    return title;
  };

  const headers = [
    {
      id: 'platform',
      numeric: false,
      disablePadding: false,
      label: 'Platform',
    },
    {
      id: 'beforePeriod',
      numeric: false,
      disablePadding: false,
      label: getPeriod(date.titleDate, date.beforePeriod),
    },
    {
      id: 'afterPeriod',
      numeric: false,
      disablePadding: true,
      label: getPeriod(date.titleafterPeriod, date.afterPeriod),
    },
    {
      id: 'evolution',
      numeric: false,
      disablePadding: true,
      label: 'Evolution',
    },
  ];

  const cellTemplatesObject = {
    platform: renderPlatform,
    beforePeriod: renderSimpleRow,
    afterPeriod: renderSimpleRow,
    evolution: renderSimpleRow,
  };

  const renderRowsByHeader = (r) =>
    headers.reduce(
      (acc, cur) => ({
        ...acc,
        [cur.id]: cellTemplatesObject[cur.id](r, cur),
        id: r.platform,
        data: r,
      }),
      {}
    );

  const cellTemplatesObjectLoading = {
    platform: renderPlatformSkeleton,
    beforePeriod: renderSimpleRowSkeleton,
    afterPeriod: renderSimpleRowSkeleton,
    evolution: renderSimpleRowSkeleton,
  };

  const renderRowsByHeaderLoading = (r) =>
    headers.reduce(
      (acc, cur) => ({
        ...acc,
        [cur.id]: cellTemplatesObjectLoading[cur.id](cur),
        id: r,
      }),
      {}
    );

  const onboard = async () => {
    const res = await settingsOnboarded({
      master_email: user.email,
      access_token: user.token,
    });
    setUserPlatformData({
      onboarded: res.onboarded,
      platforms: { ...userPlatformData.platforms, ...res.platforms },
    });
    if (res.onboarded) {
      navigate('/dashboard');
    }
  };

  const navigate = useNavigate();

  useEffect(() => {
    onboard();
  }, []);

  return (
    <div className='wrapper'>
      <div className='top-inputs'>
        <RestaurantDropdownEmpty />
        <Dates isDashboard />
      </div>
      <ContainerKit>
        {!userPlatformData.onboarded && (
          <div className='dashboard-stepper'>
            <OnboardingModal propsVariables={propsVariables} />
            <OnboardingStepper
              activeStep={activeStep}
              accounts={accounts}
              openCloseModal={openCloseModal}
            />
          </div>
        )}
        <div className='block'>
          <TypographyKit className='dashboard-title'>
            {getPeriod(date.titleDate, date.beforePeriod).charAt(0).toUpperCase() +
              getPeriod(date.titleDate, date.beforePeriod).slice(1)}{' '}
            results for all Branches
          </TypographyKit>
          <TypographyKit className='dashboard-subtitle'>
            360° view of your restaurant revenue and profits
          </TypographyKit>
          <div className='dashboard-wrapper'>
            {links.map((obj: { title: string; link: string; tooltip?: string }) => (
              <Widget
                table={table}
                setTable={setTable}
                key={obj.link}
                title={obj.title}
                link={obj.link}
                metricsbeforePeriod={{}}
                metricsafterPeriod={{}}
                loading={false}
                links={links}
                tooltip={obj.tooltip}
              />
            ))}
          </div>
        </div>
        <TableRevlyNew
          renderCustomSkelton={[0, 1, 2].map(renderRowsByHeaderLoading)}
          isLoading={false}
          link={table}
          setLink={setTable}
          links={links}
          headers={headers}
          rows={[].map(renderRowsByHeader)}
        />
      </ContainerKit>
    </div>
  );
};

export default Dashboard;
